### ISSUE TITLE
feat: Count up - Allowing counting days since an event

### ISSUE THREAD

**Issue by Sandr-aa** [sk5s/countdateapp#11]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

Currently, the app only can be used as an countdown to see how much time is left until an specific date is reached.
I wanted to do the same for the time since an event has happened.

### Describe the Use Case

I can't really say what I am tracking, but my goal is to get something done until an specific date in about half an year. I wanted to track the dates since I started to get an feeling of the speed of progress. 

### Describe Preferred Solution

If an date is set in the past , the text "days until" changes to "days since" and the number of days starts adding up

**Comment by sk5s** [comment]
Thanks for your feature proposal! I think the feature you want is like:

Now(03/19)
Countup from 03/16: 3days
Countdown for 03/21: 2days

It should be quite useful. I'll add this feature to the next release :+1:
