### ISSUE TITLE
feat: Attach a picture

### ISSUE THREAD

**Issue by nutsupra** [sk5s/countdateapp#12]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

Add a picture or a short note for events.

### Describe the Use Case

❤️

**Comment by sk5s** [comment]
Thanks for your feature proposal! :+1: 
The description feature have been added in v1.5.0, and the description support markdown.
So now you can add links, images, and text to a Countdate description.

**Comment by sk5s** [comment]
https://github.com/sk5s/countdateapp/wiki/Edit-countdate-description
