### ISSUE TITLE
feat: Add desktop widget

### ISSUE THREAD

**Issue by yiont** [sk5s/countdateapp#14]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

I would like it to be added to my lanucher, so I can check it quickly without having to go to the app.

### Describe the Use Case

Click "Add Widget" in the launcher and move the countdateapp icon to the launcher, which is more intuitive and faster.

**Comment by sk5s** [comment]
Thanks for your proposal! :heart: 
I'm currently working on this feature. I hope it can be released soon.
Note: This feature won't be available on web app.

**Comment by sk5s** [comment]
![Screenshot_20230418-205536](https://user-images.githubusercontent.com/92437055/232785456-88b87fc5-8fad-42f6-b211-e76a714deec5.jpg)
