### ISSUE TITLE
Translatable ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [sk5s/countdateapp#15]
Is the app translatable and when, where are the strings to translate ?
Thanks in advance.

**Comment by sk5s** [comment]
Hello, thanks for asking this question. However, I didn't get your question very well.
If you want to help this project and add a new language option in the app then it's great.

Depends on what the language is, the code may need some change. Now the project use i18next-react to handle translate string.

**Comment by mondlicht-und-sterne** [comment]
@sk5s   Currently there are only 3 languages.
I just can't do a pull request, so I don't understand that.in which language is actually almost irrelevant.

**Comment by sk5s** [comment]
Check out this folder: https://github.com/sk5s/countdateapp/tree/main/src/i18n
