### ISSUE TITLE
feat: Ability to create recurrent events

### ISSUE THREAD

**Issue by Terkyz** [sk5s/countdateapp#16]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [x] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great to have the ability to have the counter of an event repeat after x date, for example, the last day of the month or the first day of the month.

### Describe the Use Case

I know this is probably very specific use case, but personally one of the functions I use Countdate for is to know how many days are left in the current month, or to know what day I have to pay a bill. 

### Describe Preferred Solution

A "Recurring Event" button that will make that once that day is reached, the counter reaches 0 and repeats. And when pressing this button, a "last day of the month" / "first day of the month" panel will be enabled.

Obviously this overwrites the user's date, because if the user selects for example "day 4" it is impossible that "day 4" is the beginning or end of the month".

### Additional Information

Yes I read the Contributing Guidelines but I have no idea how to do that, I don't know how to program, I only suggest functions.

**Comment by sk5s** [comment]
Thanks for your proposal! :+1: 
If i understand your request correctly, I think the feature you want is to edit the added event to add one month or some days quickly.
Then my idea is to add some quick edit button to the event detail pannel. In that way the user can edit events quickly.
