### ISSUE TITLE
Follow System Theme 

### ISSUE THREAD

**Issue by xmha97** [sk5s/countdateapp#2]
Hi, please follow the system theme.

**Comment by sk5s** [comment]
Hello, can you provide more detail on this issue. Some information like what system, browser, android version you have used. The "follow system theme" function does work for me on both of my android phone in the latest version.

Tips: A restart of the android app is required after changing the system theme.

https://user-images.githubusercontent.com/92437055/217974402-4b3471f5-b828-46d1-9ee1-c75f5b86568e.mp4

**Comment by xmha97** [comment]
I didn't know that the app required a restart.
Is it possible to change the theme instantly? (Without restart)

**Comment by sk5s** [comment]
https://github.com/ionic-team/capacitor/issues/6100

I think it can, but it's not supported by the capacitor js itself now, and I don't know how to implement by myself.
