### ISSUE TITLE
feat: Please add Months tab.

### ISSUE THREAD

**Issue by nutsupra** [sk5s/countdateapp#25]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

![](https://cdn.discordapp.com/attachments/1039194766031736893/1131885945709396019/IMG_20230721_164320.jpg)

### Describe the Use Case

I calculate the month by dividing 30 by the number of days.

**Comment by sk5s** [comment]
Thanks for your proposal! :+1:
I think this feature is quite easy to implement and useful for some situation. I will add this feature in the future release.

**Comment by nutsupra** [comment]
Thank you very much

**Comment by nutsupra** [comment]
Thank you again.
