### ISSUE TITLE
Selecting custom date is laggy

### ISSUE THREAD

**Issue by lemonadeforlife** [sk5s/countdateapp#3]
Hello Developer. It's a great app. But facing issue selecting a date for example i was selecting march 18 but it forwarding me to April. And date picking is laggy.

**Comment by sk5s** [comment]
Hi, I also notice this bug. It seems like it's an ionic bug and that they have fixed it. I'll try updating the ionic to the latest version.

**Comment by sk5s** [comment]
Now the web version is the updated version, and it seems like the issue has fixed. 🎉 
Though it's still laggy, it won't skip month now.
