### ISSUE TITLE
feat: Relative time format 

### ISSUE THREAD

**Issue by abhith** [sk5s/countdateapp#31]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

Having an additional tab where time is shown as relative format would be nice to have. 
![Screenshot_20230923_222150_Countdate](https://github.com/sk5s/countdateapp/assets/7039457/b6828655-6536-4149-93ca-98e4a5ff9e8f)

### Describe the Use Case

This format will be more useful than having tabs for months and weeks with decimals in place. 

### Describe Preferred Solution

Something similar to the attached screenshot (moments pro) 

### Describe Alternatives

-

### Related Code

-

### Additional Information

-

**Comment by sk5s** [comment]
Thanks for your proposal! ❤️ 
Since calculating how many months and days between two dates need to know how many days in each month, so the calculate method now cannot do that. This feature will be added to the road map, and will be released when available.
