### ISSUE TITLE
feat: Accent Color change

### ISSUE THREAD

**Issue by DeMoN100** [sk5s/countdateapp#8]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/sk5s/countdateapp#contributing).
- [X] I agree to follow the [Code of Conduct](https://github.com/sk5s/countdateapp/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/sk5s/countdateapp/issues) that already include this feature request, without success.

### Describe the Feature Request

Make the blue accent color customizable to any color.

### Describe the Use Case

I hate blue & I want to change it to what I like.

### Describe Preferred Solution

Put it in settings.

### Describe Alternatives

Put it in.

### Additional Information

We should be able to choose our colors.

**Comment by sk5s** [comment]
Thanks for your suggestion. I have added this feature.
Demo:

https://user-images.githubusercontent.com/92437055/220347768-b5e597e9-03b0-452e-b5ab-592032c5af12.mp4

If there isn't your color, you can provide the color you want. I'll try making it an available accent option.

**Comment by DeMoN100** [comment]
Great that you added it in however I don't understand why the colors are named primary, secondary, warning & etc those are labels for areas you would want to  color. Also instead of manually adding colors per request why not just implement a color picker?

[Reference for color picker.](https://www.geeksforgeeks.org/how-to-create-a-color-picker-tool-in-android-using-color-wheel-and-slider/)

**Comment by sk5s** [comment]
> I don't understand why the colors are named primary, secondary, warning & etc those are labels for areas you would want to color.

The options of the accent color in v1.4.2 are the default options from ionic framework.
https://ionicframework.com/docs/theming/colors

<img width="468" alt="image" src="https://user-images.githubusercontent.com/92437055/220632635-75f8527f-3033-4bfb-b131-8a9127fea5e4.png">

**Comment by sk5s** [comment]
> Also instead of manually adding colors per request why not just implement a color picker?

I did try making this possible, however I found it a lot more difficult to implement than just using ionic default color set.
It's possible to choose color from the default html color input, though. The main problem now is that I haven't found a way to apply custom color. And the text may not be seen clearly in some condition.

> [Reference for color picker.](https://www.geeksforgeeks.org/how-to-create-a-color-picker-tool-in-android-using-color-wheel-and-slider/)

The reference is an android native components. This project use ionic react, so the component cannot be accessed in the project only if there's a capacitor plugin available.

If there are someone that want improve this feature, you can open a pull request if you are willing to help.
I'll list this feature to the road map. It may be added in the future. Thanks for providing the idea.

**Comment by DeMoN100** [comment]
> > I don't understand why the colors are named primary, secondary, warning & etc those are labels for areas you would want to color.
> 
> The options of the accent color in v1.4.2 are the default options from ionic framework. https://ionicframework.com/docs/theming/colors
> 
> <img alt="image" width="468" src="https://user-images.githubusercontent.com/92437055/220632635-75f8527f-3033-4bfb-b131-8a9127fea5e4.png">

Right but as I said those labels are for the sections they are changing the colors of. Those are not the names of the colors so your confusing the options when you have it like this.
![Screenshot_20230223_143521_Countdate](https://user-images.githubusercontent.com/8564572/221012276-63ff1f7b-ee1f-4dee-ac3d-421f49349c0b.jpg)

Do you understand what I am explaining? This should be the names of the colors not sections of areas that do not exist within the app. This should say Navy Blue, Teal, Violet, Green, Yellow, Maroon, Black, Grey, & White.

**Comment by DeMoN100** [comment]
> I did try making this possible, however I found it a lot more difficult to implement than just using ionic default color set. It's possible to choose color from the default html color input, though. The main problem now is that I haven't found a way to apply custom color. And the text may not be seen clearly in some condition.
> 
A challenge this is test your skill you must. [Reference](https://tekeye.uk/android/examples/ui/android-color-picker-tutorial) may help you or [this](https://www.geeksforgeeks.org/how-to-create-a-basic-color-picker-tool-in-android/) might.

**Comment by sk5s** [comment]
> > I did try making this possible, however I found it a lot more difficult to implement than just using ionic default color set. It's possible to choose color from the default html color input, though. The main problem now is that I haven't found a way to apply custom color. And the text may not be seen clearly in some condition.
> 
> A challenge this is test your skill you must. [Reference](https://tekeye.uk/android/examples/ui/android-color-picker-tutorial) may help you or [this](https://www.geeksforgeeks.org/how-to-create-a-basic-color-picker-tool-in-android/) might.

As I said, this project is not a **native** android app.
Thanks for providing references, but the problem now is not about color picker at all.

**Comment by sk5s** [comment]
> Do you understand what I am explaining? This should be the names of the colors not sections of areas that do not exist within the app. This should say Navy Blue, Teal, Violet, Green, Yellow, Maroon, Black, Grey, & White.

Since it's not a fatal bug , the feature will be corrected and refined in the next release.
